version: "3.9"
services:
  # api:
  #   build: .
  #   depends_on:
  #     - stock-service
  #     - database
  #     - rabbitmq
  #   ports:
  #     - 3000:3000
  #   env_file: ./.env
  #   command: ["./resource/wait-for-postgres.sh", "", "/app"]
  #   networks:
  #     - app-network
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  database:
    image: postgres:latest
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
