version: "3.9"
services:
  api:
    build: .
    depends_on:
      - stock-service
      - database
    ports:
      - 3000:3000
    env_file: ./.env
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  database:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_USER=deliverymuch
      - POSTGRES_PASSWORD=deliverymuch
      - POSTGRES_DB=deliverymuch
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
